--------------------------------------------------------------------------------
-- File: A_Friends.lua
--
-- Project: YtuAI
--
-- Description:
--     This file defines the friend and foe list for the AI. It contains a
--     table (`MyFriends`) that maps player/character IDs to a specific
--     relationship status.
--
-- Usage:
--   - To add a friend:
--     Put the homunculus in standby mode (Alt+T) and stand 1 cell to the
--     west (left) of the target player.
--
--   - To remove a friend:
--     Put the homunculus in standby mode (Alt+T) and stand 1 cell to the
--     east (right) of the target player.
--
--   - To manually set a status:
--     Add a line like: `MyFriends[<ID>]=<STATUS>`
--     Where <STATUS> can be one of the following (defined in Const_.lua):
--       - FRIEND (or 1): A friendly target.
--       - NEUTRAL: A neutral target.
--       - KOS: Kill on Sight.
--       - ENEMY: An enemy, but do not initiate attack.
--       - ALLY: An allied player.
--------------------------------------------------------------------------------
MyFriends={}
-- MyFriends[123456] = ALLY -- Example of an ally
-- MyFriends[789012] = KOS  -- Example of a Kill-on-Sight target 
